server:
  port: 8090

vnpay:
  onefinPrivateKey: C:\Users\dcu\Documents\Projects\OneFin\Sources\conn-ewallet-vnpay\src\main\resources\keys\onefin_privatekey.der
  vnpayPublicKey: C:\Users\dcu\Documents\Projects\OneFin\Sources\conn-ewallet-vnpay\src\main\resources\keys\onefin_privatekey.der
  soapUrl: "dfdsf"
  partnerCode: ONEFIN

logging:
  level:
    root: info
