
package com.onefin.ewallet.vnpaySoapWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VnpSrvSoap", targetNamespace = "http://www.vnpay.vn/VnTopup/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VnpSrvSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://www.vnpay.vn/VnTopup/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param balancerequest
     * @return
     *     returns vn.vnpay.vntopup.BalanceResponse
     */
    @WebMethod(operationName = "GetBalance", action = "http://www.vnpay.vn/VnTopup/GetBalance")
    @WebResult(name = "GetBalanceResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "GetBalance", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetBalance")
    @ResponseWrapper(localName = "GetBalanceResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetBalanceResponse")
    public BalanceResponse getBalance(
        @WebParam(name = "balancerequest", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        Balance balancerequest);

    /**
     * 
     * @param topuprequest
     * @return
     *     returns vn.vnpay.vntopup.TopupResponse
     */
    @WebMethod(operationName = "TopupMobile", action = "http://www.vnpay.vn/VnTopup/TopupMobile")
    @WebResult(name = "TopupMobileResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "TopupMobile", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.TopupMobile")
    @ResponseWrapper(localName = "TopupMobileResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.TopupMobileResponse")
    public TopupResponse topupMobile(
        @WebParam(name = "topuprequest", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        Topup topuprequest);

    /**
     * 
     * @param localDateTime
     * @param amount
     * @param trace
     * @param productCode
     * @param partnerCode
     * @param sign
     * @return
     *     returns vn.vnpay.vntopup.CardResponse
     */
    @WebMethod(operationName = "GetCard", action = "http://www.vnpay.vn/VnTopup/GetCard")
    @WebResult(name = "GetCardResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "GetCard", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetCard")
    @ResponseWrapper(localName = "GetCardResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetCardResponse")
    public CardResponse getCard(
        @WebParam(name = "PartnerCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String partnerCode,
        @WebParam(name = "ProductCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String productCode,
        @WebParam(name = "Amount", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String amount,
        @WebParam(name = "Trace", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        long trace,
        @WebParam(name = "LocalDateTime", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String localDateTime,
        @WebParam(name = "Sign", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String sign);

    /**
     * 
     * @param localDateTime
     * @param amount
     * @param trace
     * @param productCode
     * @param partnerCode
     * @param sign
     * @param mobileNo
     * @return
     *     returns vn.vnpay.vntopup.CardResponse
     */
    @WebMethod(operationName = "GetCardToMobile", action = "http://www.vnpay.vn/VnTopup/GetCardToMobile")
    @WebResult(name = "GetCardToMobileResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "GetCardToMobile", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetCardToMobile")
    @ResponseWrapper(localName = "GetCardToMobileResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetCardToMobileResponse")
    public CardResponse getCardToMobile(
        @WebParam(name = "PartnerCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String partnerCode,
        @WebParam(name = "ProductCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String productCode,
        @WebParam(name = "Amount", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String amount,
        @WebParam(name = "Trace", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        long trace,
        @WebParam(name = "MobileNo", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String mobileNo,
        @WebParam(name = "LocalDateTime", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String localDateTime,
        @WebParam(name = "Sign", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String sign);

    /**
     * 
     * @param transaction
     * @return
     *     returns vn.vnpay.vntopup.TransqueryResponse
     */
    @WebMethod(operationName = "GetTransaction", action = "http://www.vnpay.vn/VnTopup/GetTransaction")
    @WebResult(name = "GetTransactionResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "GetTransaction", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetTransaction")
    @ResponseWrapper(localName = "GetTransactionResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetTransactionResponse")
    public TransqueryResponse getTransaction(
        @WebParam(name = "transaction", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        Transaction transaction);

    /**
     * 
     * @param sTrace
     * @param sLocalDateTime
     * @param sPartnerCode
     * @param sSign
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTransactionCard", action = "http://www.vnpay.vn/VnTopup/GetTransactionCard")
    @WebResult(name = "GetTransactionCardResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "GetTransactionCard", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetTransactionCard")
    @ResponseWrapper(localName = "GetTransactionCardResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetTransactionCardResponse")
    public String getTransactionCard(
        @WebParam(name = "sPartnerCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String sPartnerCode,
        @WebParam(name = "sTrace", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String sTrace,
        @WebParam(name = "sLocalDateTime", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String sLocalDateTime,
        @WebParam(name = "sSign", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String sSign);

    /**
     * 
     * @param sPartnerCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMaxTrace", action = "http://www.vnpay.vn/VnTopup/GetMaxTrace")
    @WebResult(name = "GetMaxTraceResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "GetMaxTrace", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetMaxTrace")
    @ResponseWrapper(localName = "GetMaxTraceResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetMaxTraceResponse")
    public String getMaxTrace(
        @WebParam(name = "sPartnerCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String sPartnerCode);

    /**
     * 
     * @param signData
     * @param product
     * @param total
     * @param trace
     * @param partnerCode
     * @param unitCode
     * @return
     *     returns vn.vnpay.vntopup.CardListResponse
     */
    @WebMethod(operationName = "GetCardList", action = "http://www.vnpay.vn/VnTopup/GetCardList")
    @WebResult(name = "GetCardListResult", targetNamespace = "http://www.vnpay.vn/VnTopup/")
    @RequestWrapper(localName = "GetCardList", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetCardList")
    @ResponseWrapper(localName = "GetCardListResponse", targetNamespace = "http://www.vnpay.vn/VnTopup/", className = "vn.vnpay.vntopup.GetCardListResponse")
    public CardListResponse getCardList(
        @WebParam(name = "PartnerCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String partnerCode,
        @WebParam(name = "Product", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String product,
        @WebParam(name = "Total", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        int total,
        @WebParam(name = "UnitCode", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        int unitCode,
        @WebParam(name = "Trace", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        int trace,
        @WebParam(name = "SignData", targetNamespace = "http://www.vnpay.vn/VnTopup/")
        String signData);

}
