
package com.onefin.ewallet.vnpaySoapWebService;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VnpSrv", targetNamespace = "http://www.vnpay.vn/VnTopup/", wsdlLocation = "http://210.245.12.220:19061/VnTopupService/VnpSrv.asmx?WSDL")
public class VnpSrv
    extends Service
{

    private final static URL VNPSRV_WSDL_LOCATION;
    private final static WebServiceException VNPSRV_EXCEPTION;
    private final static QName VNPSRV_QNAME = new QName("http://www.vnpay.vn/VnTopup/", "VnpSrv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://210.245.12.220:19061/VnTopupService/VnpSrv.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VNPSRV_WSDL_LOCATION = url;
        VNPSRV_EXCEPTION = e;
    }

    public VnpSrv() {
        super(__getWsdlLocation(), VNPSRV_QNAME);
    }

    public VnpSrv(WebServiceFeature... features) {
        super(__getWsdlLocation(), VNPSRV_QNAME, features);
    }

    public VnpSrv(URL wsdlLocation) {
        super(wsdlLocation, VNPSRV_QNAME);
    }

    public VnpSrv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VNPSRV_QNAME, features);
    }

    public VnpSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VnpSrv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VnpSrvSoap
     */
    @WebEndpoint(name = "VnpSrvSoap")
    public VnpSrvSoap getVnpSrvSoap() {
        return super.getPort(new QName("http://www.vnpay.vn/VnTopup/", "VnpSrvSoap"), VnpSrvSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VnpSrvSoap
     */
    @WebEndpoint(name = "VnpSrvSoap")
    public VnpSrvSoap getVnpSrvSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.vnpay.vn/VnTopup/", "VnpSrvSoap"), VnpSrvSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns VnpSrvSoap
     */
    @WebEndpoint(name = "VnpSrvSoap12")
    public VnpSrvSoap getVnpSrvSoap12() {
        return super.getPort(new QName("http://www.vnpay.vn/VnTopup/", "VnpSrvSoap12"), VnpSrvSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VnpSrvSoap
     */
    @WebEndpoint(name = "VnpSrvSoap12")
    public VnpSrvSoap getVnpSrvSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.vnpay.vn/VnTopup/", "VnpSrvSoap12"), VnpSrvSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VNPSRV_EXCEPTION!= null) {
            throw VNPSRV_EXCEPTION;
        }
        return VNPSRV_WSDL_LOCATION;
    }

}
